apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: payments-app-secret
  namespace: app-payments
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: vault-kv-dc-payments
  target:
    name: payments-app-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: apps/payments/prod
        property: username
    - secretKey: password
      remoteRef:
        key: apps/payments/prod
        property: password
