apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-kv-dc-payments
  namespace: app-payments
spec:
  provider:
    vault:
      server: https://vault-dc.bank.example.com:8200
      path: kv-dc
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes-dc
          role: eso-kv-readonly-dc
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
