apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-pki-ingress-dr
spec:
  vault:
    path: pki-ingress-dr/sign/role-istio-gateway-dr
    server: https://vault-dr.bank.example.com:8200
    caBundle: REPLACE_ME_BASE64_CA_BUNDLE
    auth:
      kubernetes:
        mountPath: /v1/auth/kubernetes-dr
        role: cert-manager-pki-issuer-dr
        serviceAccountRef:
          name: cert-manager
