apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-kv-app-sample
  namespace: app-sample
spec:
  provider:
    vault:
      server: REPLACE_ME_VAULT_ADDR
      path: REPLACE_ME_VAULT_KV_MOUNT
      version: v2
      caBundle: REPLACE_ME_BASE64_CA_BUNDLE
      auth:
        kubernetes:
          mountPath: REPLACE_ME_VAULT_K8S_AUTH_MOUNT
          role: app-sample-kv-readonly
          serviceAccountRef:
            name: sample-api
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sample-api-app-secret
  namespace: app-sample
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-kv-app-sample
    kind: SecretStore
  target:
    name: sample-api-app-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: apps/sample-api/prod
        property: username
    - secretKey: password
      remoteRef:
        key: apps/sample-api/prod
        property: password
