apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-namespaces.yaml
  - 01-istio-control-plane.yaml
  - 02-istio-cni.yaml
  - 03-ztunnel.yaml
  - 04-platform-pki-and-secrets.yaml
  - 05-gateway-api-ingress.yaml
  - 06-gateway-api-routes.yaml
  - 07-egress-gateway-and-external-service.yaml
  - 08-sample-app.yaml
  - 09-sample-app-secrets.yaml
  - 10-wso2-internal-certificate.yaml
