apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-kv-dr-platform
spec:
  provider:
    vault:
      server: https://vault-dr.bank.example.com:8200
      path: kv-dr
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes-dr
          role: eso-kv-readonly-dr
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
